apiVersion: v1
kind: Service
metadata:
  name: lanchonete-pagamento
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: lanchonete-pagamento
  ports:
    - name: http
      port: 80
      targetPort: 8080